/**
 * Copyright (C) 2016 Bruno Candido Volpato da Cunha (brunocvcunha@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.brunocvcunha.instagram4j;

import lombok.Getter;
import lombok.Setter;

/**
 *
 * Instagram4j API
 * 
 * @author Bruno Candido Volpato da Cunha
 *
 */
public class InstagramConstants {

	/**
	 * API URL
	 */
	public static final String API_URL = "https://i.instagram.com/api/v1/";

	/**
	 * API Key (extracted from the apk)
	 */
	// public static final String API_KEY =
	// "f372b2a5f14d1bebedaaa4ac6f8d506db30ffdd6185b8e0cdfa7dab42f5a9cc6";
	public static final String API_KEY = "4fedfba2a33dee3bdc43fa26d5e934b60e97f3e194e503fe57df2a3dd43bb28f";

	/**
	 * API Key Version
	 */
	public static final String API_KEY_VERSION = "4";

	/**
	 * Device
	 */
	@Getter
	private static Device device = Device.GOOD_DEVICES[0];

	/**
	 * Device to mimic
	 */
	@Deprecated
	public static String DEVICE_MANUFACTURER = device.getDEVICE_MANUFACTURER();

	/**
	 * Model to mimic
	 */
	@Deprecated
	public static String DEVICE_MODEL = device.getDEVICE_MODEL();

	/**
	 * Android version to mimic
	 */
	@Deprecated
	public static String DEVICE_ANDROID_VERSION = device.getDEVICE_ANDROID_VERSION();

	/**
	 * Android Release
	 */
	@Deprecated
	public static String DEVICE_ANDROID_RELEASE = device.getDEVICE_ANDROID_RELEASE();

	/**
	 * Experiments Activated
	 */
	// public static final String DEVICE_EXPERIMENTS =
	// "ig_android_universe_video_production,ig_search_client_h1_2017_holdout,ig_android_carousel_non_square_creation,ig_android_live_analytics,ig_android_realtime_mqtt_logging,ig_branded_content_show_settings_universe,ig_android_stories_server_coverframe,ig_android_live_dash_predictive_streaming,ig_android_video_captions_universe,ig_business_growth_acquisition_holdout_17h2,ig_android_ontact_invite_universe,ig_android_ad_async_ads_universe,ig_android_shopping_tag_creation_carousel_universe,ig_feed_engagement_holdout_universe,ig_direct_pending_inbox_memcache,ig_promote_guided_budget_duration_options_universe,ig_android_verified_comments_universe,ig_feed_lockdown,android_instagram_prefetch_suggestions_universe,ig_android_gallery_order_by_date_taken,ig_shopping_viewer_intent_actions,ig_android_startup_prefetch,ig_android_business_post_insights_v3_universe,ig_android_custom_story_import_intent,ig_video_copyright_whitelist,ig_explore_holdout_universe,ig_android_device_language_reset,ig_android_videocall_consumption_universe,ig_android_live_fault_tolerance_universe,ig_android_main_feed_seen_state_dont_send_info_on_tail_load,ig_android_face_filter_glyph_nux_animation_universe,ig_android_direct_allow_consecutive_likes,ig_android_livewith_guest_adaptive_camera_universe,ig_android_business_new_ads_payment_universe,ig_android_audience_control,ig_promotion_insights_sticky_tab_universe,ig_android_unified_bindergroup_in_staticandpagedadapter,ig_android_ad_new_viewability_logging_universe,ig_android_ad_impression_backtest,ig_android_log_account_switch_usable,ig_android_mas_viewer_list_megaphone_universe,ig_android_photo_fbupload_universe,ig_android_carousel_drafts,ig_android_bug_report_version_warning,ig_fbns_push,ig_android_carousel_no_buffer_10_30,ig_android_sso_family_key,ig_android_profile_tabs_redesign_universe,ig_android_user_url_deeplink_fbpage_endpoint,ig_android_fix_slow_rendering,ig_android_hide_post_in_feed,ig_android_shopping_thumbnail_icon,ig_android_ad_watchbrowse_universe,ig_android_search_people_tag_universe,ig_android_codec_high_profile,ig_android_long_impression_tracking,ig_android_inline_appeal,ig_android_log_mediacodec_info,ig_android_direct_expiring_media_loading_errors,ig_android_camera_face_filter_api_retry,ig_video_use_sve_universe,ig_android_low_data_mode,ig_android_enable_zero_rating,ig_android_sample_ppr,ig_android_force_logout_user_with_mismatched_cookie,ig_android_smartisan_app_badging,ig_android_direct_expiring_media_fix_duplicate_thread,ig_android_reverse_audio,ig_android_branded_content_three_line_ui_universe,ig_android_comments_impression_logger,ig_android_live_encore_production_universe,ig_promote_independent_ctas_universe,ig_android_http_stack_experiment_2017,ig_android_pending_request_search_bar,ig_android_main_feed_carousel_bumping_animation,ig_android_live_thread_delay_for_mute_universe,ig_android_fb_topsearch_sgp_fork_request,ig_android_heap_uploads,ig_android_stories_archive_universe,ig_android_business_ix_fb_autofill_universe,ig_lockdown_feed_shrink_universe,ig_android_stories_create_flow_favorites_tooltip,ig_android_direct_ephemeral_replies_with_context,ig_android_live_viewer_invite_universe,ig_android_promotion_feedback_channel,ig_profile_holdout_2017_universe,ig_android_executor_null_queue,ig_android_stories_video_loading_spinner_improvements,ig_android_direct_share_intent,ig_android_live_capture_translucent_navigation_bar,ig_stories_camera_blur_drawable,ig_android_stories_drawing_sticker,ig_android_facebook_twitter_profile_photos,ig_android_shopping_tag_creation_universe,ig_android_story_decor_image_fbupload_universe,ig_android_comments_ranking_kill_switch_universe,ig_promote_profile_visit_cta_universe,ig_android_story_reactions,ig_android_ppr_main_feed_enhancements,ig_android_used_jpeg_library,ig_carousel_draft_multiselect,ig_android_stories_close_to_left_head,ig_android_video_delay_auto_start,ig_android_live_with_invite_sheet_search_universe,ig_android_stories_archive_calendar,ig_android_ad_watchbrowse_cta_universe,ig_android_ads_manager_pause_resume_ads_universe,ig_android_main_feed_carousel_bumping,ig_stories_in_feed_unit_design_universe,ig_android_explore_iteminfo_universe_exp,ig_android_me_only_universe,ig_android_live_video_reactions_consumption_universe,ig_android_stories_hashtag_text,ig_android_live_reply_to_comments_universe,ig_android_live_save_to_camera_roll_universe,ig_android_sticker_region_tracking,ig_android_unified_inbox,ig_android_realtime_iris,ig_android_search_client_matching_2,ig_lockdown_notifications_universe,ig_android_feed_seen_state_with_view_info,ig_android_media_rows_prepare_10_31,ig_family_bridges_holdout_universe,ig_android_background_explore_fetch,ig_android_following_follower_social_context,ig_android_live_auto_collapse_comments_view_universe,ig_android_insta_video_consumption_infra,ig_android_ad_watchlead_universe,ig_android_direct_prefetch_direct_story_json,ig_android_cache_logger_10_34,ig_android_stories_weblink_creation,ig_android_histogram_reporter,ig_android_network_cancellation,ig_android_shopping_show_shop_tooltip,ig_android_video_delay_auto_start_threshold,ig_android_comment_category_filter_setting_universe,ig_promote_daily_budget_universe,ig_android_stories_camera_enhancements,ig_android_video_use_new_logging_arch,ig_android_ad_add_per_event_counter_to_logging_event,ig_android_feed_stale_check_interval,ig_android_crop_from_inline_gallery_universe,ig_android_direct_reel_options_entry_point,ig_android_stories_gallery_improvements,ig_android_live_broadcaster_invite_universe,ig_android_inline_photos_of_you_universe,ig_android_prefetch_notification_data,ig_android_direct_full_size_gallery_upload_universe_v2,ig_android_direct_app_deeplinking,ig_promotions_unit_in_insights_landing_page,ig_android_reactive_feed_like_count,ig_android_camera_ff_story_open_tray,ig_android_stories_asset_search,ig_android_constrain_image_size_universe,ig_rn_top_posts_stories_nux_universe,ig_ranking_following,ig_android_camera_retain_face_filter,ig_android_direct_inbox_presence,ig_android_live_skin_smooth,ig_android_stories_posting_offline_ui,ig_android_sidecar_video_upload_universe,ig_android_canvas_swipe_to_open_universe,ig_android_qp_features,android_ig_stories_without_storage_permission_universe2,ig_android_reel_raven_video_segmented_upload_universe,ig_android_swipe_navigation_x_angle_universe,ig_android_invite_xout_universe,ig_android_offline_mode_holdout,ig_android_live_send_user_location,ig_android_live_encore_go_live_button_universe,ig_android_analytics_logger_running_background_universe,ig_android_save_all,ig_android_live_report_watch_time_when_update,ig_android_family_bridge_discover,ig_android_startup_manager,instagram_search_and_coefficient_holdout,ig_android_high_res_upload_2,ig_android_dynamic_background_prefetch,ig_android_http_service_same_thread,ig_android_scroll_to_dismiss_keyboard,ig_android_remove_followers_universe,ig_android_skip_video_render,ig_android_crash_native_core_dumping,ig_android_one_tap_nux_upsell,ig_android_segmentation,ig_profile_holdout_universe,ig_dextricks_module_loading_experiment,ig_android_comments_composer_avatar_universe,ig_android_direct_open_thread_with_expiring_media,ig_android_post_capture_filter,ig_android_rendering_controls,ig_android_os_version_blocking,ig_android_no_prefetch_video_bandwidth_threshold,ig_android_encoder_width_safe_multiple_16,ig_android_warm_like_text,ig_android_request_feed_on_back,ig_comments_team_holdout_universe,ig_android_e2e_optimization_universe,ig_shopping_insights,ig_android_direct_async_message_row_building_universe,ig_android_fb_connect_follow_invite_flow,ig_android_direct_24h_replays,ig_android_video_stitch_after_segmenting_universe,ig_android_instavideo_periodic_notif,ig_android_enable_swipe_to_dismiss_for_all_dialogs,ig_android_stories_camera_support_image_keyboard,ig_android_warm_start_fetch_universe,ig_android_marauder_update_frequency,ig_camera_android_aml_face_tracker_model_version_universe,ig_android_ad_connection_manager_universe,ig_android_ad_watchbrowse_carousel_universe,ig_android_branded_content_edit_flow_universe,ig_android_video_feed_universe,ig_android_upload_reliability_universe,ig_android_direct_mutation_manager_universe,ig_android_ad_show_new_bakeoff,ig_heart_with_keyboad_exposed_universe,ig_android_react_native_universe_kill_switch,ig_android_comments_composer_callout_universe,ig_android_search_hash_tag_and_username_universe,ig_android_live_disable_speed_test_ui_timeout_universe,ig_android_miui_notification_badging,ig_android_qp_kill_switch,ig_android_ad_switch_fragment_logging_v2_universe,ig_android_ad_leadgen_single_screen_universe,ig_android_share_to_whatsapp,ig_android_live_snapshot_universe,ig_branded_content_share_to_facebook,ig_android_react_native_email_sms_settings_universe,ig_android_live_join_comment_ui_change,ig_android_camera_tap_smile_icon_to_selfie_universe,ig_android_feed_surface_universe,ig_android_biz_choose_category,ig_android_prominent_live_button_in_camera_universe,ig_android_video_cover_frame_from_original_as_fallback,ig_android_camera_leak_detector_universe,ig_android_live_hide_countdown_universe,ig_android_story_viewer_linear_preloading_count,ig_android_threaded_comments_universe,ig_android_stories_search_reel_mentions_universe,ig_promote_reach_destinations_universe,ig_android_progressive_jpeg_partial_download,ig_fbns_shared,ig_android_capture_slowmo_mode,ig_android_live_ff_fill_gap,ig_promote_clicks_estimate_universe,ig_android_video_single_surface,ig_android_video_download_logging,ig_android_foreground_location_collection,ig_android_last_edits,ig_android_pending_actions_serialization,ig_android_post_live_viewer_count_privacy_universe,ig_stories_engagement_2017_h2_holdout_universe,ig_android_image_cache_tweak_for_n,ig_android_direct_increased_notification_priority,ig_android_search_top_search_surface_universe,ig_android_live_dash_latency_manager,instagram_interests_holdout,ig_android_user_detail_endpoint,ig_android_videocall_production_universe,ig_android_ad_watchmore_entry_point_universe,ig_android_video_detail,ig_save_insights,ig_camera_android_new_face_effects_api_universe,ig_comments_typing_universe,ig_android_exoplayer_settings,ig_android_progressive_jpeg,ig_android_offline_story_stickers,ig_android_live_webrtc_audience_expansion_universe,ig_explore_android_universe,ig_android_video_prefetch_for_connectivity_type,ig_android_ad_holdout_watchandmore_universe,ig_promote_default_cta,ig_direct_stories_recipient_picker_button,ig_android_direct_notification_lights,ig_android_insights_relay_modern,ig_android_insta_video_abr_resize,ig_android_insta_video_sound_always_on,ig_android_fb_content_provider_anr_fix,ig_android_in_app_notifications_queue,ig_android_live_follow_from_comments_universe,ig_android_comments_new_like_button_position_universe,ig_android_hyperzoom,ig_android_live_broadcast_blacklist,ig_android_camera_perceived_perf_universe,ig_android_search_clear_layout_universe,ig_promote_reachbar_universe,ig_android_ad_one_pixel_logging_for_reel_universe,ig_android_stories_surface_universe,ig_android_stories_highlights_universe,ig_android_reel_viewer_fetch_missing_reels_universe,ig_android_arengine_separate_prepare,ig_android_direct_video_segmented_upload_universe,ig_android_direct_search_share_sheet_universe,ig_android_business_promote_tooltip,ig_android_direct_blue_tab,ig_android_instavideo_remove_nux_comments,ig_android_draw_rainbow_client_universe,ig_android_use_simple_video_player,ig_android_rtc_reshare,ig_android_enable_swipe_to_dismiss_for_favorites_dialogs,ig_android_auto_retry_post_mode,ig_fbns_preload_default,ig_android_emoji_sprite_sheet,ig_android_cover_frame_blacklist,ig_android_gesture_dismiss_reel_viewer,ig_android_gallery_grid_column_count_universe,ig_android_ad_logger_funnel_logging_universe,ig_android_live_encore_consumption_settings_universe,ig_perf_android_holdout,ig_android_list_redesign,ig_android_stories_separate_overlay_creation,ig_android_ad_show_new_interest_survey,ig_android_live_encore_reel_chaining_universe,ig_android_vod_abr_universe,ig_android_audience_profile_icon_badge,ig_android_immersive_viewer,ig_android_analytics_use_a2,ig_android_react_native_universe,ig_android_direct_thread_name_as_notification,ig_android_su_rows_preparer,ig_android_leak_detector_universe,ig_android_video_loopcount_int,ig_android_qp_sticky_exposure_universe,ig_android_enable_main_feed_reel_tray_preloading,ig_android_camera_upsell_dialog,ig_android_live_time_adjustment_universe,ig_android_internal_research_settings,ig_android_prod_lockout_universe,ig_android_react_native_ota,ig_android_main_camera_share_to_direct,ig_android_cold_start_feed_request,ig_android_fb_family_navigation_badging_user,ig_stories_music_sticker,ig_android_send_impression_via_real_time,ig_android_sc_ru_ig,ig_android_animation_perf_reporter_timeout,ig_android_warm_headline_text,ig_android_post_live_expanded_comments_view_universe,ig_android_new_block_flow,ig_android_long_form_video,ig_android_sign_video_url,ig_android_image_task_cancel_logic_fix,ig_android_stories_video_prefetch_kb,ig_android_video_render_prevent_cancellation_feed_universe,ig_android_live_stop_broadcast_on_404,android_face_filter_universe,ig_android_render_iframe_interval,ig_business_claim_page_universe,ig_android_live_move_video_with_keyboard_universe,ig_stories_vertical_list,ig_android_stories_server_brushes,ig_android_live_viewers_canned_comments_universe,ig_android_collections_cache,ig_android_payment_settings_universe,ig_android_live_face_filter,ig_android_canvas_preview_universe,ig_android_screen_recording_bugreport_universe,ig_story_camera_reverse_video_experiment,ig_downloadable_modules_experiment,ig_direct_core_holdout_q4_2017,ig_promote_updated_copy_universe,ig_android_search,ig_android_logging_metric_universe,ig_promote_budget_duration_slider_universe,ig_android_insta_video_consumption_titles,ig_android_video_proxy,ig_android_find_loaded_classes,ig_android_direct_expiring_media_replayable,ig_android_reduce_rect_allocation,ig_android_camera_universe,ig_android_post_live_badge_universe,ig_stories_holdout_h2_2017,ig_android_video_server_coverframe,ig_promote_relay_modern,ig_android_search_users_universe,ig_android_video_controls_universe,ig_creation_growth_holdout,android_segmentation_filter_universe,ig_qp_tooltip,ig_android_live_encore_consumption_universe,ig_android_experimental_filters,ig_android_shopping_profile_shoppable_feed,ig_android_save_collection_pivots,ig_android_business_conversion_value_prop_v2,ig_android_ad_browser_warm_up_improvement_universe,ig_promote_guided_ad_preview_newscreen,ig_android_livewith_universe,ig_android_whatsapp_invite_option,ig_android_video_keep_screen_on,ig_promote_automatic_audience_universe,ig_android_direct_remove_animations,ig_android_live_align_by_2_universe,ig_android_friend_code,ig_android_top_live_profile_pics_universe,ig_android_async_network_tweak_universe_15,ig_android_direct_init_post_launch,ig_android_camera_new_early_show_smile_icon_universe,ig_android_live_go_live_at_viewer_end_screen_universe,ig_android_live_bg_download_face_filter_assets_universe,ig_android_background_reel_fetch,ig_android_insta_video_audio_encoder,ig_android_video_segmented_media_needs_reupload_universe,ig_promote_budget_duration_split_universe,ig_android_upload_prevent_upscale,ig_android_business_ix_universe,ig_android_ad_browser_new_tti_universe,ig_android_self_story_layout,ig_android_business_choose_page_ui_universe,ig_android_camera_face_filter_animation_on_capture,ig_android_rtl,ig_android_comment_inline_expansion_universe,ig_android_live_request_to_join_production_universe,ig_android_share_spinner,ig_android_video_resize_operation,ig_android_stories_eyedropper_color_picker,ig_android_disable_explore_prefetch,ig_android_universe_reel_video_production,ig_android_react_native_push_settings_refactor_universe,ig_android_power_metrics,ig_android_sfplt,ig_android_story_resharing_universe,ig_android_direct_inbox_search,ig_android_direct_share_story_to_facebook,ig_android_exoplayer_creation_flow,ig_android_non_square_first,ig_android_insta_video_drawing,ig_android_swipeablefilters_universe,ig_android_direct_visual_replies_fifty_fifty,ig_android_reel_viewer_data_buffer_size,ig_android_video_segmented_upload_multi_thread_universe,ig_android_react_native_restart_after_error_universe,ig_android_direct_notification_actions,ig_android_profile,ig_android_additional_contact_in_nux,ig_stories_selfie_sticker,ig_android_live_use_rtc_upload_universe,ig_android_story_reactions_producer_holdout,ig_android_stories_reply_composer_redesign,ig_android_story_viewer_segments_bar_universe,ig_explore_netego,ig_android_audience_control_sharecut_universe,ig_android_direct_fix_top_of_thread_scrolling,ig_video_holdout_h2_2017,ig_android_insights_metrics_graph_universe,ig_android_ad_swipe_up_threshold_universe,ig_android_one_tap_send_sheet_universe,ig_android_international_add_payment_flow_universe,ig_android_live_see_fewer_videos_like_this_universe,ig_android_live_view_profile_from_comments_universe,ig_fbns_blocked,ig_android_direct_inbox_suggestions,ig_android_video_segmented_upload_universe,ig_carousel_post_creation_tag_universe,ig_android_mqtt_region_hint_universe,ig_android_suggest_password_reset_on_oneclick_login,ig_android_live_special_codec_size_list,ig_android_continuous_contact_uploading,ig_android_story_viewer_item_duration_universe,ig_promote_budget_duration_client_server_switch,ig_android_enable_share_to_messenger,ig_android_background_main_feed_fetch,promote_media_picker,ig_android_live_video_reactions_creation_universe,ig_android_sidecar_gallery_universe,ig_android_business_id,ig_android_story_import_intent,ig_android_feed_follow_button_redesign,ig_android_section_based_recipient_list_universe,ig_android_insta_video_broadcaster_infra_perf,ig_android_live_webrtc_livewith_params,ig_android_comment_audience_control_group_selection_universe,android_ig_fbns_kill_switch,ig_android_su_card_view_preparer_qe,ig_android_unified_camera_universe,ig_android_all_videoplayback_persisting_sound,ig_android_live_pause_upload,ig_android_branded_content_brand_remove_self,ig_android_direct_search_recipients_controller_universe,ig_android_ad_show_full_name_universe,ig_android_anrwatchdog,ig_android_camera_video_universe,ig_android_2fac,ig_android_audio_segment_report_info,ig_android_scroll_main_feed,ig_direct_bypass_group_size_limit_universe,ig_android_story_captured_media_recovery,ig_android_skywalker_live_event_start_end,ig_android_comment_hint_text_universe,ig_android_direct_search_story_recipients_universe,ig_android_ad_browser_gesture_control,ig_android_grid_cell_count,ig_promote_marketing_funnel_universe,ig_android_immersive_viewer_ufi_footer,ig_android_ad_watchinstall_universe,ig_android_comments_notifications_universe,ig_android_shortcuts,ig_android_new_optic,ig_android_audience_control_nux,favorites_home_inline_adding,ig_android_canvas_tilt_to_pan_universe,ig_internal_ui_for_lazy_loaded_modules_experiment,ig_android_direct_expiring_media_from_notification_behavior_universe,ig_android_fbupload_check_status_code_universe,ig_android_offline_reel_feed,ig_android_stories_viewer_modal_activity,ig_android_shopping_creation_flow_onboarding_entry_point,ig_android_activity_feed_click_state,ig_android_direct_expiring_image_quality_universe,ig_android_gl_drawing_marks_after_undo_backing,ig_android_story_gallery_behavior,ig_android_mark_seen_state_on_viewed_impression,ig_android_configurable_retry,ig_android_live_monotonic_pts,ig_android_live_webrtc_livewith_h264_supported_decoders,ig_story_ptr_timeout,ig_android_comment_tweaks_universe,ig_android_location_media_count_exp_ig,ig_android_image_cache_log_mismatch_fetch,ig_android_personalized_feed_universe,ig_android_direct_double_tap_to_like_messages,ig_android_comment_activity_feed_deeplink_to_comments_universe,ig_android_insights_holdout,ig_android_video_render_prevent_cancellation,ig_android_blue_token_conversion_universe,ig_android_tabbed_hashtags_locations_universe,ig_android_sfplt_tombstone,ig_android_live_with_guest_viewer_list_universe,ig_android_explore_chaining_universe,ig_android_gqls_typing_indicator,ig_android_comment_audience_control_universe,ig_android_direct_show_inbox_loading_banner_universe,ig_android_near_bottom_fetch,ig_promote_guided_creation_flow,ig_ads_increase_connection_step2_v2,ig_android_draw_chalk_client_universe";

	public static final String DEVICE_EXPERIMENTS = "ig_android_sticker_search_explorations,android_ig_camera_ar_asset_manager"
			+ "_improvements_universe,ig_android_stories_seen_state_serialization,ig_sto"
			+ "ries_photo_time_duration_universe,ig_android_bitmap_cache_executor_size,i"
			+ "g_android_stories_music_search_typeahead,ig_android_delayed_comments,ig_a"
			+ "ndroid_switch_back_option,ig_android_video_profiler_loom_traces,ig_androi"
			+ "d_paid_branded_content_rendering,ig_android_direct_app_reel_grid_search,i"
			+ "g_android_stories_no_inflation_on_app_start,ig_android_camera_sdk_check_g"
			+ "l_surface_r2,ig_promote_review_screen_title_universe,ig_android_direct_ne"
			+ "wer_single_line_composer_universe,ig_direct_holdout_h1_2019,ig_explore_20"
			+ "19_h1_destination_cover,ig_android_direct_stories_in_direct_inbox,ig_fb_g"
			+ "raph_differentiation_no_fb_data,ig_android_recyclerview_binder_group_enab"
			+ "led_universe,ig_android_direct_share_sheet_custom_fast_scroller,ig_androi"
			+ "d_video_exoplayer_2,ig_android_shopping_channel_in_explore,ig_android_sto"
			+ "ries_music_filters,ig_android_2018_h1_hashtag_report_universe,ig_android_"
			+ "live_replay_highlights_universe,ig_android_hashtag_page_reduced_related_i"
			+ "tems,ig_android_live_titles_broadcaster_side_create_title_universe,ig_and"
			+ "roid_fbns_preload_direct_universe,ig_android_prefetch_carousels_on_swipe_"
			+ "universe,ig_camera_network_activity_logger,ig_camera_remove_display_rotat"
			+ "ion_cb_universe,ig_android_interactions_migrate_inline_composer_to_viewpo"
			+ "int_universe,ig_android_realtime_always_start_connection_on_condition_uni"
			+ "verse,ig_android_ad_leadgen_single_screen_universe,ig_android_enable_zero"
			+ "_rating,ig_android_import_page_post_after_biz_conversion,ig_camera_ar_eff"
			+ "ect_attribution_position,ig_android_vc_call_ended_cleanup_universe,ig_sto"
			+ "ries_engagement_holdout_2019_h1_universe,ig_android_story_import_intent,i"
			+ "g_direct_report_conversation_universe,ig_biz_graph_connection_universe,ig"
			+ "_android_codec_high_profile,ig_android_nametag,ig_android_sso_family_key_"
			+ "universe,ig_android_parse_direct_messages_bytes_universe,ig_hashtag_creat"
			+ "ion_universe,ig_android_gallery_order_by_date_taken,ig_android_igtv_resha"
			+ "re,ig_end_of_feed_universe,ig_android_share_others_post_reorder,ig_androi"
			+ "d_additional_contact_in_nux,ig_android_live_use_all_preview_sizes,ig_andr"
			+ "oid_clarify_invite_options,ig_android_live_align_by_2_universe,ig_android"
			+ "_separate_network_executor,ig_android_realtime_manager_optimization,ig_an"
			+ "droid_auto_advance_su_unit_when_scrolled_off_screen,ig_android_network_ca"
			+ "ncellation,ig_android_media_as_sticker,ig_android_stories_video_prefetch_"
			+ "kb,ig_android_maintabfragment,ig_inventory_connections,ig_stories_injecti"
			+ "on_tool_enabled_universe,ig_android_stories_disable_highlights_media_prel"
			+ "oading,ig_android_live_start_broadcast_optimized_universe,ig_android_stor"
			+ "ies_question_response_mutation_universe,ig_android_onetap_upsell_change_p"
			+ "wd,ig_nametag_data_collection,ig_android_disable_scroll_listeners,ig_andr"
			+ "oid_persistent_nux,ig_android_igtv_audio_always_on,ig_android_enable_lige"
			+ "r_preconnect_universe,ig_android_persistent_duplicate_notif_checker_user_"
			+ "based,ig_android_rate_limit_mediafeedviewablehelper,ig_android_search_rem"
			+ "ove_null_state_sections,ig_android_stories_viewer_drawable_cache_universe"
			+ ",ig_direct_android_reply_modal_universe,ig_android_biz_qp_suggest_page,ig"
			+ "_shopping_indicator_content_variations_android,ig_android_stories_reel_me"
			+ "dia_item_automatic_retry,ig_fb_notification_universe,ig_android_live_disa"
			+ "ble_speed_test_ui_timeout_universe,ig_android_direct_thread_scroll_perf_o"
			+ "ncreate_universe,ig_android_low_data_mode_backup_2,ig_android_invite_xout"
			+ "_universe,ig_android_low_data_mode_backup_3,ig_android_low_data_mode_back"
			+ "up_4,ig_android_low_data_mode_backup_5,ig_android_video_abr_universe,ig_a"
			+ "ndroid_low_data_mode_backup_1,ig_android_signup_refactor_santity,ig_chall"
			+ "enge_general_v2,ig_android_place_signature_universe,ig_android_hide_butto"
			+ "n_for_invite_facebook_friends,ig_android_business_promote_tooltip,ig_andr"
			+ "oid_follow_requests_ui_improvements,ig_android_shopping_post_tagging_nux_"
			+ "universe,ig_android_stories_sensitivity_screen,ig_android_camera_arengine"
			+ "_shader_caching_universe,ig_android_insta_video_broadcaster_infra_perf,ig"
			+ "_android_direct_view_more_qe,ig_android_direct_visual_message_prefetch_co"
			+ "unt_universe,ig_camera_android_ar_effect_stories_deeplink,ig_android_clie"
			+ "nt_side_delivery_universe,ig_android_stories_send_client_reels_on_tray_fe"
			+ "tch_universe,ig_android_direct_inbox_background_view_models,ig_android_st"
			+ "artup_thread_priority,ig_android_stories_viewer_responsiveness_universe,i"
			+ "g_android_live_use_rtc_upload_universe,ig_android_live_ama_viewer_univers"
			+ "e,ig_android_business_id_conversion_universe,ig_smb_ads_holdout_2018_h2_u"
			+ "niverse,ig_android_modal_activity_no_animation_fix_universe,ig_android_ca"
			+ "mera_post_smile_low_end_universe,ig_android_live_realtime_comments_univer"
			+ "se,ig_android_vc_in_app_notification_universe,ig_eof_caboose_universe,ig_"
			+ "android_new_one_tap_nux_universe,ig_android_igds_edit_profile_fields,ig_a"
			+ "ndroid_downgrade_viewport_exit_behavior,ig_android_mi_batch_upload_univer"
			+ "se,ig_camera_android_segmentation_async_universe,ig_android_use_recyclerv"
			+ "iew_for_direct_search_universe,ig_android_live_comment_fetch_frequency_un"
			+ "iverse,ig_android_create_page_on_top_universe,ig_android_direct_log_badge"
			+ "_count_inconsistent,ig_android_stories_text_format_emphasis,ig_android_qu"
			+ "estion_sticker_replied_state,ig_android_ad_connection_manager_universe,ig"
			+ "_android_image_upload_skip_queue_only_on_wifi,ig_android_ad_watchbrowse_c"
			+ "arousel_universe,ig_android_interactions_show_verified_badge_for_preview_"
			+ "comments_universe,ig_stories_question_sticker_music_format_prompt,ig_andr"
			+ "oid_activity_feed_row_click,ig_android_hide_crashing_newsfeed_story_t3813"
			+ "1972,ig_android_video_upload_quality_qe1,ig_android_save_collaborative_co"
			+ "llections,ig_android_location_attribution_text,ig_camera_android_profile_"
			+ "ar_notification_universe,coupon_price_test_boost_instagram_media_acquisit"
			+ "ion_universe,ig_android_video_outputsurface_handlerthread_universe,ig_and"
			+ "roid_country_code_fix_universe,ig_perf_android_holdout_2018_h1,ig_android"
			+ "_stories_music_overlay,ig_android_enable_lean_crash_reporting_universe,ig"
			+ "_android_resumable_downloads_logging_universe,ig_android_stories_default_"
			+ "rear_camera_universe,ig_android_low_latency_consumption_universe,ig_andro"
			+ "id_offline_mode_holdout,ig_android_foreground_location_collection,ig_andr"
			+ "oid_stories_close_friends_disable_first_time_badge,ig_android_react_nativ"
			+ "e_universe_kill_switch,ig_android_video_ta_universe,ig_android_media_rows"
			+ "_async_inflate,ig_android_stories_gallery_video_segmentation,ig_android_s"
			+ "tories_in_feed_preview_notify_fix_universe,ig_android_video_rebind_force_"
			+ "keep_playing_fix,ig_android_direct_business_holdout,ig_android_xposting_u"
			+ "psell_directly_after_sharing_to_story,ig_android_gallery_high_quality_pho"
			+ "to_thumbnails,ig_android_interactions_new_comment_like_pos_universe,ig_fe"
			+ "ed_core_experience_universe,ig_android_friends_sticker,ig_android_busines"
			+ "s_ix_universe,ig_android_suggested_highlights,ig_android_stories_posting_"
			+ "offline_ui,ig_android_stories_close_friends_rings_remove_green_universe,i"
			+ "g_android_canvas_tilt_to_pan_universe,ig_android_vc_background_call_toast"
			+ "_universe,ig_android_concurrent_cold_start_universe,ig_promote_default_de"
			+ "stination_universe,mi_viewpoint_viewability_universe,ig_android_location_"
			+ "page_info_page_upsell,igds_android_listrow_migration_universe,ig_direct_r"
			+ "eshare_sharesheet_ranking,ig_android_fb_sync_options_universe,ig_android_"
			+ "drawable_usage_logging_universe,ig_android_recommend_accounts_destination"
			+ "_routing_fix,ig_android_fix_prepare_direct_push,ig_direct_android_larger_"
			+ "media_reshare_style,ig_android_video_feed_universe,ig_android_building_ay"
			+ "mf_universe,ig_android_internal_sticker_universe,ig_traffic_routing_unive"
			+ "rse,ig_android_search_normalization,ig_android_ad_watchmore_entry_point_u"
			+ "niverse,ig_camera_android_segmentation_enabled_universe,ig_android_igtv_a"
			+ "lways_show_browse_ui,ig_android_page_claim_deeplink_qe,ig_explore_2018_h2"
			+ "_account_rec_deduplication_android,ig_android_story_accidentally_click_in"
			+ "vestigation_universe,ig_android_shopping_pdp_hero_carousel,ig_android_cle"
			+ "ar_inflight_image_request,ig_android_show_su_in_other_users_follow_list,i"
			+ "g_android_stories_infeed_lower_threshold_launch,ig_android_main_feed_vide"
			+ "o_countdown_timer,instagram_interests_holdout,ig_android_continuous_video"
			+ "_capture,ig_android_category_search_edit_profile,ig_android_contact_invit"
			+ "es_nux_universe,ig_android_settings_search_v2_universe,ig_android_video_u"
			+ "pload_iframe_interval,ig_business_new_value_prop_universe,ig_android_powe"
			+ "r_metrics,ig_android_stories_collapse_seen_segments,ig_android_live_follo"
			+ "w_from_comments_universe,ig_android_hashtag_discover_tab,ig_android_live_"
			+ "skip_live_encoder_pts_correction,ig_android_reel_zoom_universe,enable_cre"
			+ "ator_account_conversion_v0_universe,ig_android_test_not_signing_address_b"
			+ "ook_unlink_endpoint,ig_android_direct_tabbed_media_picker,ig_android_dire"
			+ "ct_mutation_manager_job_scheduler,ig_ei_option_setting_universe,ig_androi"
			+ "d_hashtag_related_items_over_logging,ig_android_livewith_liveswap_optimiz"
			+ "ation_universe,ig_android_direct_new_intro_card,ig_camera_android_support"
			+ "ed_capabilities_api_universe,ig_android_video_webrtc_textureview,ig_andro"
			+ "id_share_claim_page_universe,ig_direct_android_mentions_sender,ig_android"
			+ "_whats_app_contact_invite_universe,ig_android_video_scrubber_thumbnail_un"
			+ "iverse,ig_camera_ar_image_transform_library,ig_android_insights_creation_"
			+ "growth_universe,ig_android_igtv_refresh_tv_guide_interval,ig_android_stor"
			+ "ies_gif_sticker,ig_android_stories_music_broadcast_receiver,ig_android_fb"
			+ "_profile_integration_fbnc_universe,ig_android_low_data_mode,ig_fb_graph_d"
			+ "ifferentiation_control,ig_android_show_create_content_pages_universe,ig_a"
			+ "ndroid_igsystrace_universe,ig_android_new_contact_invites_entry_points_un"
			+ "iverse,ig_android_ccu_jobscheduler_inner,ig_android_netego_scroll_perf,ig"
			+ "_android_fb_connect_follow_invite_flow,ig_android_invite_list_button_rede"
			+ "sign_universe,ig_android_react_native_email_sms_settings_universe,ig_andr"
			+ "oid_igtv_aspect_ratio_limits,ig_hero_player,ig_android_save_auto_sharing_"
			+ "to_fb_option_on_server,ig_android_live_presence_universe,ig_android_white"
			+ "hat_options_universe,android_cameracore_preview_frame_listener2_ig_univer"
			+ "se,ig_android_memory_manager,ig_account_recs_in_chaining,ig_explore_2018_"
			+ "finite_chain_android_universe,ig_android_tagging_video_preview,ig_android"
			+ "_feed_survey_viewpoint,ig_android_hashtag_search_suggestions,ig_android_p"
			+ "rofile_neue_infra_rollout_universe,ig_android_instacrash_detection,ig_and"
			+ "roid_interactions_add_search_bar_to_likes_list_universe,ig_android_vc_cap"
			+ "ture_universe,ig_nametag_local_ocr_universe,ig_branded_content_share_to_f"
			+ "acebook,ig_android_direct_segmented_video,ig_android_search_page_v2,ig_an"
			+ "droid_stories_recently_captured_universe,ig_business_integrity_ipc_univer"
			+ "se,ig_android_share_product_universe,ig_fb_graph_differentiation_top_k_fb"
			+ "_coefficients,ig_shopping_viewer_share_action,ig_android_direct_share_sto"
			+ "ry_to_facebook,ig_android_business_attribute_sync,ig_android_video_time_t"
			+ "o_live_cache_eviction,ig_android_location_feed_related_business,ig_androi"
			+ "d_view_and_likes_cta_universe,ig_live_holdout_h2_2018,ig_android_profile_"
			+ "memories_universe,ig_promote_budget_warning_view_universe,ig_android_redi"
			+ "rect_to_web_on_oembed_fail_universe,ig_android_optic_new_focus_controller"
			+ ",ig_android_shortcuts,ig_android_search_hashtag_badges,ig_android_navigat"
			+ "ion_latency_logger,ig_android_direct_composer_avoid_hiding_thread_camera,"
			+ "ig_android_direct_remix_visual_messages,ig_android_custom_story_import_in"
			+ "tent,ig_android_biz_new_choose_category,ig_android_view_info_universe,ig_"
			+ "android_camera_upsell_dialog,ig_android_business_ix_self_serve,ig_android"
			+ "_dead_code_detection,ig_android_ad_watchbrowse_universe,ig_android_pbia_p"
			+ "roxy_profile_universe,ig_android_qp_kill_switch,ig_android_gap_rule_enfor"
			+ "cer_universe,ig_android_direct_delete_or_block_from_message_requests,ig_a"
			+ "ndroid_direct_left_aligned_navigation_bar,ig_android_feed_load_more_viewp"
			+ "oint_universe,ig_android_stories_reshare_reply_msg,ig_android_one_tap_sha"
			+ "resheet_fb_extensions,ig_android_stories_feeback_message_composer_entry_p"
			+ "oint,ig_direct_holdout_h2_2018,ig_camera_android_facetracker_v12_universe"
			+ ",ig_android_camera_ar_effects_low_storage_universe,ig_camera_android_blac"
			+ "k_feed_sticker_fix_universe,ig_android_direct_media_forwarding,ig_android"
			+ "_camera_attribution_in_direct,ig_android_audience_control,ig_android_stor"
			+ "ies_cross_sharing_to_fb_holdout_universe,ig_android_enable_main_feed_reel"
			+ "_tray_preloading,ig_android_profile_neue_universe,ig_company_profile_hold"
			+ "out,ig_camera_android_areffect_photo_capture_universe,ig_rti_inapp_notifi"
			+ "cations_universe,ig_android_vc_join_timeout_universe,ig_android_feed_core"
			+ "_ads_2019_h1_holdout_universe,ig_android_interactions_composer_mention_se"
			+ "arch_universe,ig_android_igtv_save,ig_android_follower_following_whatsapp"
			+ "_invite_universe,ig_android_claim_location_page,ig_android_story_ads_2019"
			+ "_h1_holdout_universe,ig_android_3pspp,ig_android_cache_timespan_objects,i"
			+ "g_timestamp_public_test,ig_android_histogram_reporter,ig_android_feed_aut"
			+ "o_share_to_facebook_dialog,ig_android_arengine_separate_prepare,ig_androi"
			+ "d_skip_button_content_on_connect_fb_universe,ig_android_igtv_profile_tab,"
			+ "ig_android_show_fb_name_universe,ig_android_interactions_inline_composer_"
			+ "extensions_universe,ig_camera_async_space_validation_for_ar,ig_android_pi"
			+ "geon_sampling,ig_story_camera_reverse_video_experiment,ig_android_live_us"
			+ "e_timestamp_normalizer,ig_android_profile_lazy_load_carousel_media,ig_and"
			+ "roid_stories_question_sticker_music_format,ig_business_profile_18h1_holdo"
			+ "ut_universe,ig_pacing_overriding_universe,ig_android_direct_allow_multili"
			+ "ne_composition,ig_android_interactions_emoji_extension_followup_universe,"
			+ "ig_android_story_ads_direct_cta_universe,ig_android_q3lc_transparency_con"
			+ "trol_settings,ig_stories_selfie_sticker,ig_android_sso_use_trustedapp_uni"
			+ "verse,ig_android_ad_increase_story_adpreload_priority_universe,ig_android"
			+ "_interests_netego_dismiss,ig_direct_giphy_gifs_rating,ig_android_shopping"
			+ "_catalogsearch,ig_android_stories_music_awareness_universe,ig_android_qcc"
			+ "_perf,ig_android_stories_reels_tray_media_count_check,ig_android_new_fb_p"
			+ "age_selection,ig_android_facebook_crosspost,ig_android_internal_collab_sa"
			+ "ve,ig_video_holdout_h2_2017,ig_android_story_sharing_universe,ig_promote_"
			+ "post_insights_entry_universe,ig_android_direct_thread_store_rewrite,ig_an"
			+ "droid_qp_clash_management_enabled_v4_universe,ig_branded_content_paid_bra"
			+ "nded_content,ig_android_large_heap_override,ig_android_live_subscribe_use"
			+ "r_level_universe,ig_android_igtv_creation_flow,ig_android_video_call_fini"
			+ "sh_universe,ig_android_direct_mqtt_send,ig_android_do_not_fetch_follow_re"
			+ "quests_on_success,ig_android_remove_push_notifications,ig_android_vc_dire"
			+ "ctapp_integration_universe,ig_android_explore_discover_people_entry_point"
			+ "_universe,ig_android_sonar_prober_universe,ig_android_live_bg_download_fa"
			+ "ce_filter_assets_universe,ig_android_gif_framerate_throttling,ig_android_"
			+ "live_webrtc_livewith_params,ig_android_vc_always_start_connection_on_cond"
			+ "ition_universe,ig_camera_worldtracking_set_scale_by_arclass,ig_android_di"
			+ "rect_inbox_typing_indicator,ig_android_stories_music_lyrics_scrubber,ig_f"
			+ "eed_experience,ig_android_direct_new_thread_local_search_fix_universe,ig_"
			+ "android_appstate_logger,ig_promote_insights_video_views_universe,ig_andro"
			+ "id_dismiss_recent_searches,ig_android_downloadable_igrtc_module,ig_androi"
			+ "d_fb_link_ui_polish_universe,ig_stories_music_sticker,ig_android_device_c"
			+ "apability_framework,ig_scroll_by_two_cards_for_suggested_invite_universe,"
			+ "ig_android_stories_helium_balloon_badging_universe,ig_android_business_re"
			+ "move_unowned_fb_pages,ig_android_stories_combined_asset_search,ig_stories"
			+ "_allow_camera_actions_while_recording,ig_android_analytics_mark_events_as"
			+ "_offscreen,ig_android_optic_feature_testing,ig_android_camera_universe,ig"
			+ "_android_optic_photo_cropping_fixes,ig_camera_regiontracking_use_similari"
			+ "ty_tracker_for_scaling,ig_android_refreshable_list_view_check_spring,feli"
			+ "x_android_video_quality,ig_android_biz_endpoint_switch,ig_android_direct_"
			+ "continuous_capture,ig_android_comments_direct_reply_to_author,ig_android_"
			+ "vc_webrtc_params,ig_android_claim_or_connect_page_on_xpost,ig_android_anr"
			+ ",ig_android_optic_new_architecture,ig_android_stories_viewer_as_modal_hig"
			+ "h_end_launch,ig_android_hashtag_follow_chaining_over_logging,ig_new_eof_d"
			+ "emarcator_universe,ig_android_push_notifications_settings_redesign_univer"
			+ "se,ig_hashtag_display_universe,ig_fbns_push,coupon_price_test_ad4ad_insta"
			+ "gram_resurrection_universe,ig_android_live_rendering_looper_universe,ig_a"
			+ "ndroid_mqtt_cookie_auth_memcache_universe,ig_android_live_end_redirect_un"
			+ "iverse,ig_android_direct_mutation_manager_media_2,ig_android_ccu_jobsched"
			+ "uler_outer,ig_smb_ads_holdout_2019_h1_universe,ig_fb_graph_differentiatio"
			+ "n,ig_android_stories_share_extension_video_segmentation,ig_android_intera"
			+ "ctions_realtime_typing_indicator_and_live_comments,ig_android_stories_cre"
			+ "ate_flow_favorites_tooltip,ig_android_live_nerd_stats_universe,ig_android"
			+ "_universe_video_production,ig_android_hide_reset_with_fb_universe,ig_andr"
			+ "oid_reactive_feed_like_count,ig_android_stories_music_precapture,ig_andro"
			+ "id_vc_service_crash_fix_universe,ig_android_shopping_product_overlay,ig_a"
			+ "ndroid_direct_double_tap_to_like_hearts,ig_camera_android_api_rewrite_uni"
			+ "verse,ig_android_growth_fci_team_holdout_universe,ig_android_stories_gall"
			+ "ery_recyclerview_kit_universe,ig_android_story_ads_instant_sub_impression"
			+ "_universe,ig_business_signup_biz_id_universe,ig_android_save_all,ig_andro"
			+ "id_main_feed_fragment_scroll_timing_histogram_uni,ig_android_ttcp_improve"
			+ "ments,ig_android_camera_ar_platform_profile_universe,ig_explore_2018_topi"
			+ "c_channel_navigation_android_universe,ig_android_live_fault_tolerance_uni"
			+ "verse,ig_android_stories_viewer_tall_android_cap_media_universe,native_co"
			+ "ntact_invites_universe,ig_android_dash_script,ig_android_insights_media_h"
			+ "ashtag_insight_universe,ig_camera_fast_tti_universe,ig_android_stories_wh"
			+ "atsapp_share,ig_android_inappnotification_rootactivity_tweak,ig_android_r"
			+ "ender_thread_memory_leak_holdout,ig_android_private_highlights_universe,i"
			+ "g_android_rate_limit_feed_video_module,ig_android_one_tap_fbshare,ig_shar"
			+ "e_to_story_toggle_include_shopping_product,ig_android_direct_speed_cam_un"
			+ "iv,ig_payments_billing_address,ig_android_ufiv3_holdout,ig_android_new_ca"
			+ "mera_design_container_animations_universe,ig_android_livewith_guest_adapt"
			+ "ive_camera_universe,ig_android_direct_fix_playing_invalid_visual_message,"
			+ "ig_shopping_viewer_intent_actions,ig_promote_add_payment_navigation_unive"
			+ "rse,ig_android_optic_disable_post_capture_preview_restart,ig_android_main"
			+ "_feed_refresh_style_universe,ig_android_live_analytics,ig_android_story_a"
			+ "ds_performance_universe_1,ig_android_stories_viewer_modal_activity,ig_and"
			+ "roid_story_ads_performance_universe_3,ig_android_story_ads_performance_un"
			+ "iverse_4,ig_android_feed_seen_state_with_view_info,ig_android_ads_profile"
			+ "_cta_feed_universe,ig_android_vc_cowatch_universe,ig_android_optic_thread"
			+ "_priorities,ig_android_igtv_chaining,ig_android_live_qa_viewer_v1_univers"
			+ "e,ig_android_stories_show_story_not_available_error_msg,ig_android_inline"
			+ "_notifications_recommended_user,ig_shopping_post_insights,ig_android_webr"
			+ "tc_streamid_salt_universe,ig_android_wellbeing_timeinapp_v1_universe,ig_a"
			+ "ndroid_profile_cta_v3,ig_android_video_qp_logger_universe,ig_android_cach"
			+ "e_video_autoplay_checker,ig_android_live_suggested_live_expansion,ig_andr"
			+ "oid_vc_start_from_direct_inbox_universe,ig_perf_android_holdout,ig_fb_gra"
			+ "ph_differentiation_only_fb_candidates,ig_android_expired_build_lockout,ig"
			+ "_promote_lotus_universe,ig_android_video_streaming_upload_universe,ig_and"
			+ "roid_optic_fast_preview_restart_listener,ig_interactions_h1_2019_team_hol"
			+ "dout_universe,ig_android_ad_async_ads_universe,ig_camera_android_effect_i"
			+ "nfo_bottom_sheet_universe,ig_android_stories_feedback_badging_universe,ig"
			+ "_android_sorting_on_self_following_universe,ig_android_edit_location_page"
			+ "_info,ig_promote_are_you_sure_universe,ig_android_interactions_feed_label"
			+ "_below_comments_refactor_universe,ig_android_camera_platform_effect_share"
			+ "_universe,ig_stories_engagement_swipe_animation_simple_universe,ig_login_"
			+ "activity,ig_android_direct_quick_replies,ig_android_fbns_optimization_uni"
			+ "verse,ig_android_stories_alignment_guides_universe,ig_android_rn_ads_mana"
			+ "ger_universe,ig_explore_2018_post_chaining_account_recs_dedupe_universe,i"
			+ "g_android_click_to_direct_story_reaction_universe,ig_internal_research_se"
			+ "ttings,ig_android_stories_video_seeking_audio_bug_fix,ig_android_insights"
			+ "_holdout,ig_android_swipe_up_area_universe,ig_android_rendering_controls,"
			+ "ig_android_feed_post_sticker,ig_android_inline_editing_local_prefill,ig_a"
			+ "ndroid_hybrid_bitmap_v3_prenougat,ig_android_cronet_stack,ig_android_enab"
			+ "le_igrtc_module,ig_android_scroll_audio_priority,ig_android_shopping_prod"
			+ "uct_appeals_universe,ig_android_fb_follow_server_linkage_universe,ig_andr"
			+ "oid_fblocation_universe,ig_android_direct_updated_story_reference_ui,ig_c"
			+ "amera_holdout_h1_2018_product,live_with_request_to_join_button_universe,i"
			+ "g_android_music_continuous_capture,ig_android_churned_find_friends_redire"
			+ "ct_to_discover_people,ig_android_main_feed_new_posts_indicator_universe,i"
			+ "g_vp9_hd_blacklist,ig_ios_queue_time_qpl_universe,ig_android_split_contac"
			+ "ts_list,ig_android_connect_owned_page_universe,ig_android_felix_prefetch_"
			+ "thumbnail_sprite_sheet,ig_android_multi_dex_class_loader_v2,ig_android_wa"
			+ "tch_and_more_redesign,igtv_feed_previews,ig_android_qp_batch_fetch_cachin"
			+ "g_enabled_v1_universe,ig_android_profile_edit_phone_universe,ig_android_v"
			+ "c_renderer_type_universe,ig_android_local_2018_h2_holdout,ig_android_purx"
			+ "_native_checkout_universe,ig_android_vc_disable_lock_screen_content_acces"
			+ "s_universe,ig_android_business_transaction_in_stories_creator,android_cam"
			+ "eracore_ard_ig_integration,ig_video_experimental_encoding_consumption_uni"
			+ "verse,ig_android_iab_autofill,ig_android_location_page_intent_survey,ig_c"
			+ "amera_android_segmentation_qe2_universe,ig_android_image_mem_cache_strong"
			+ "_ref_universe,ig_android_business_promote_refresh_fb_access_token_univers"
			+ "e,ig_android_stories_samsung_sharing_integration,ig_android_hashtag_heade"
			+ "r_display,ig_discovery_holdout_2019_h1_universe,ig_android_user_url_deepl"
			+ "ink_fbpage_endpoint,ig_android_direct_mutation_manager_handler_thread_uni"
			+ "verse,ig_branded_content_show_settings_universe,ig_android_ad_holdout_wat"
			+ "chandmore_universe,ig_android_direct_thread_green_dot_presence_universe,i"
			+ "g_android_camera_new_post_smile_universe,ig_android_shopping_signup_redes"
			+ "ign_universe,ig_android_vc_missed_call_notification_action_reply,allow_pu"
			+ "blish_page_universe,ig_android_experimental_onetap_dialogs_universe,ig_pr"
			+ "omote_ppe_v2_universe,android_cameracore_ig_gl_oom_fixes_universe,ig_andr"
			+ "oid_multi_capture_camera,ig_android_fb_family_navigation_badging_user,ig_"
			+ "android_follow_requests_copy_improvements,ig_media_geo_gating,ig_android_"
			+ "comments_notifications_universe,ig_android_render_output_surface_timeout_"
			+ "universe,ig_android_drop_frame_check_paused,ig_direct_raven_sharesheet_ra"
			+ "nking,ig_android_realtime_mqtt_logging,ig_family_bridges_holdout_universe"
			+ ",ig_android_rainbow_hashtags,ig_android_ad_watchinstall_universe,ig_andro"
			+ "id_ad_account_top_followers_universe,ig_android_betamap_universe,ig_andro"
			+ "id_video_ssim_report_universe,ig_android_cache_network_util,ig_android_le"
			+ "ak_detector_upload_universe,ig_android_carousel_prefetch_bumping,ig_fbns_"
			+ "preload_default,ig_android_inline_appeal_show_new_content,ig_fbns_kill_sw"
			+ "itch,ig_hashtag_following_holdout_universe,ig_android_show_weekly_ci_upse"
			+ "ll_limit,ig_android_direct_reel_options_entry_point_2_universe,enable_cre"
			+ "ator_account_conversion_v0_animation,ig_android_http_service_same_thread,"
			+ "ig_camera_holdout_h1_2018_performance,ig_android_direct_mutation_manager_"
			+ "cancel_fix_universe,ig_music_dash,ig_android_fb_url_universe,ig_android_r"
			+ "eel_raven_video_segmented_upload_universe,ig_android_promote_native_migra"
			+ "tion_universe,ig_camera_android_badge_face_effects_universe,ig_android_hy"
			+ "brid_bitmap_v3_nougat,ig_android_multi_author_story_reshare_universe,ig_a"
			+ "ndroid_vc_camera_zoom_universe,ig_android_enable_request_compression_ccu,"
			+ "ig_android_video_controls_universe,ig_android_logging_metric_universe_v2,"
			+ "ig_android_xposting_newly_fbc_people,ig_android_visualcomposer_inapp_noti"
			+ "fication_universe,ig_android_contact_point_upload_rate_limit_killswitch,i"
			+ "g_android_webrtc_encoder_factory_universe,ig_android_search_impression_lo"
			+ "gging,ig_android_handle_username_in_media_urls_universe,ig_android_sso_ko"
			+ "totoro_app_universe,ig_android_mi_holdout_h1_2019,ig_android_igtv_autopla"
			+ "y_on_prepare,ig_file_based_session_handler_2_universe,ig_branded_content_"
			+ "tagging_upsell,ig_shopping_insights_parity_universe_android,ig_android_li"
			+ "ve_ama_universe,ig_android_external_gallery_import_affordance,ig_android_"
			+ "updatelistview_on_loadmore,ig_android_optic_new_zoom_controller,ig_androi"
			+ "d_hide_type_mode_camera_button,ig_android_photos_qpl,ig_android_reel_impr"
			+ "esssion_cache_key_qe_universe,ig_android_show_profile_picture_upsell_in_r"
			+ "eel_universe,ig_android_live_viewer_tap_to_hide_chrome_universe,ig_discov"
			+ "ery_holdout_universe,ig_android_direct_import_google_photos2,ig_android_s"
			+ "tories_tray_in_viewer,ig_android_request_verification_badge,ig_android_di"
			+ "rect_unlimited_raven_replays_inthreadsession_fix,ig_android_netgo_cta,ig_"
			+ "android_viewpoint_netego_universe,ig_android_stories_separate_overlay_cre"
			+ "ation,ig_android_iris_improvements,ig_android_biz_conversion_naming_test,"
			+ "ig_android_fci_empty_feed_friend_search,ig_android_hashtag_page_support_p"
			+ "laces_tab,ig_camera_android_ar_platform_universe,ig_android_stories_viewe"
			+ "r_prefetch_improvements,ig_android_optic_camera_warmup,ig_android_place_s"
			+ "earch_profile_image,ig_android_interactions_in_feed_comment_view_universe"
			+ ",ig_android_fb_sharing_shortcut,ig_android_oreo_hardware_bitmap,ig_androi"
			+ "d_analytics_diagnostics_universe,ig_android_insights_creative_tutorials_u"
			+ "niverse,ig_android_vc_universe,ig_android_profile_unified_follow_view,ig_"
			+ "android_collect_os_usage_events_universe,ig_android_shopping_nux_timing_u"
			+ "niverse,ig_android_fbpage_on_profile_side_tray,ig_android_native_logcat_i"
			+ "nterceptor,ig_android_direct_thread_content_picker,ig_android_notif_impro"
			+ "vement_universe,ig_face_effect_ranking,ig_android_shopping_more_from_busi"
			+ "ness,ig_feed_content_universe,ig_android_hacked_account_reporting,ig_andr"
			+ "oid_disk_usage_logging_universe,ig_android_ad_redesign_iab_universe,ig_an"
			+ "droid_banyan_migration,ig_android_profile_event_leak_holdout,ig_android_s"
			+ "tories_loading_automatic_retry,ig_android_gqls_typing_indicator,ag_family"
			+ "_bridges_2018_h2_holdout,ig_promote_net_promoter_score_universe,ig_androi"
			+ "d_direct_last_seen_message_indicator,ig_android_biz_conversion_suggest_bi"
			+ "z_nux,ig_android_log_mediacodec_info,ig_android_vc_participant_state_call"
			+ "ee_universe,ig_camera_android_boomerang_attribution_universe,ig_android_s"
			+ "tories_weblink_creation,ig_android_horizontal_swipe_lfd_logging,ig_profil"
			+ "e_company_holdout_h2_2018,ig_android_ads_manager_pause_resume_ads_univers"
			+ "e,ig_promote_fix_expired_fb_accesstoken_android_universe,ig_android_stori"
			+ "es_media_seen_batching_universe,ig_android_interactions_nav_to_permalink_"
			+ "followup_universe,ig_android_live_titles_viewer_side_view_title_universe,"
			+ "ig_android_direct_mark_as_read_notif_action,ig_android_edit_highlight_red"
			+ "esign,ig_android_direct_mutation_manager_backoff_universe,ig_android_inte"
			+ "ractions_comment_like_for_all_feed_universe,ig_android_mi_skip_analytic_e"
			+ "vent_pool_universe,ig_android_fbc_upsell_on_dp_first_load,ig_android_audi"
			+ "o_ingestion_params,ig_android_video_call_participant_state_caller_univers"
			+ "e,ig_fbns_shared,ig_feed_engagement_holdout_2018_h1,ig_camera_android_bg_"
			+ "processor,ig_android_optic_new_features_implementation,ig_android_stories"
			+ "_reel_interactive_tap_target_size,ig_android_video_live_trace_universe,ig"
			+ "_android_igtv_browse_with_pip_v2,ig_android_interactive_listview_during_r"
			+ "efresh,ig_android_igtv_feed_banner_universe,ig_android_unfollow_from_main"
			+ "_feed_v2,ig_android_self_story_setting_option_in_menu,ig_android_ad_watch"
			+ "lead_universe,ufi_share,ig_android_live_special_codec_size_list,ig_androi"
			+ "d_live_qa_broadcaster_v1_universe,ig_android_hide_stories_viewer_list_uni"
			+ "verse,ig_android_direct_albums,ig_android_business_transaction_in_stories"
			+ "_consumer,ig_android_scroll_stories_tray_to_front_when_stories_ready,ig_a"
			+ "ndroid_direct_thread_composer,instagram_android_stories_sticker_tray_rede"
			+ "sign,ig_camera_android_superzoom_icon_position_universe,ig_android_busine"
			+ "ss_cross_post_with_biz_id_infra,ig_android_photo_invites,ig_android_reel_"
			+ "tray_item_impression_logging_viewpoint,ig_account_identity_2018_h2_lockdo"
			+ "wn_phone_global_holdout,ig_android_high_res_gif_stickers,ig_close_friends"
			+ "_v4,ig_fb_cross_posting_sender_side_holdout,ig_android_ads_history_univer"
			+ "se,ig_android_comments_composer_newline_universe,ig_rtc_use_dtls_srtp,ig_"
			+ "promote_media_picker_universe,ig_android_live_start_live_button_universe,"
			+ "ig_android_vc_ongoing_call_notification_universe,ig_android_rate_limit_fe"
			+ "ed_item_viewable_helper,ig_android_bitmap_attribution_check,ig_android_ig"
			+ "_to_fb_sync_universe,ig_android_reel_viewer_data_buffer_size,ig_two_fac_t"
			+ "otp_enable,ig_android_vc_missed_call_notification_action_call_back,ig_and"
			+ "roid_stories_landscape_mode,ig_android_ad_view_ads_native_universe,ig_and"
			+ "roid_igtv_whitelisted_for_web,ig_android_global_prefetch_scheduler,ig_and"
			+ "roid_live_thread_delay_for_mute_universe,ig_close_friends_v4_global,ig_an"
			+ "droid_share_publish_page_universe,ig_android_new_camera_design_universe,i"
			+ "g_direct_max_participants,ig_promote_hide_local_awareness_universe,ig_and"
			+ "roid_graphql_survey_new_proxy_universe,ig_android_fs_creation_flow_tweaks"
			+ ",ig_android_ad_watchbrowse_cta_universe,ig_android_camera_new_tray_behavi"
			+ "or_universe,ig_android_direct_expiring_media_loading_errors,ig_android_sh"
			+ "ow_fbunlink_button_based_on_server_data,ig_android_downloadable_vp8_modul"
			+ "e,ig_android_igtv_feed_trailer,ig_android_fb_profile_integration_universe"
			+ ",ig_android_profile_private_banner,ig_camera_android_focus_attribution_un"
			+ "iverse,ig_android_rage_shake_whitelist,ig_android_su_follow_back,ig_andro"
			+ "id_prefetch_notification_data,ig_android_webrtc_icerestart_on_failure_uni"
			+ "verse,ig_android_vpvd_impressions_universe,ig_android_payload_based_sched"
			+ "uling,ig_android_grid_cell_count,ig_android_new_highlight_button_text,ig_"
			+ "android_direct_search_bar_redesign,ig_android_hashtag_row_preparer,ig_and"
			+ "roid_ad_pbia_header_click_universe,ig_android_direct_visual_viewer_ppr_fi"
			+ "x,ig_background_prefetch,ig_camera_android_focus_in_post_universe,ig_andr"
			+ "oid_time_spent_dashboard,ig_android_direct_vm_activity_sheet,ig_promote_p"
			+ "olitical_ads_universe,ig_android_stories_auto_retry_reels_media_and_segme"
			+ "nts,ig_android_recommend_accounts_killswitch,ig_shopping_video_half_sheet"
			+ ",ig_android_ad_iab_qpl_kill_switch_universe,ig_android_interactions_direc"
			+ "t_share_comment_universe,ig_android_vc_sounds_universe,ig_camera_android_"
			+ "cache_format_picker_children,ig_android_post_live_expanded_comments_view_"
			+ "universe,ig_android_always_use_server_recents,ig_android_qp_slot_cooldown"
			+ "_enabled_universe,ig_android_asset_picker_improvements,ig_android_direct_"
			+ "activator_cards,ig_android_pending_media_manager_init_fix_universe,ig_and"
			+ "roid_facebook_global_state_sync_frequency_universe,ig_android_network_tra"
			+ "ce_migration,ig_android_creation_new_post_title,ig_android_reverse_audio,"
			+ "ig_android_camera_gallery_upload_we_universe,ig_android_direct_inbox_asyn"
			+ "c_diffing_universe,ig_android_live_save_to_camera_roll_limit_by_screen_si"
			+ "ze_universe,ig_android_profile_phone_autoconfirm_universe,ig_direct_stori"
			+ "es_questions,ig_android_optic_surface_texture_cleanup,ig_android_vc_use_t"
			+ "imestamp_normalizer,ig_android_post_recs_show_more_button_universe,ig_sho"
			+ "pping_checkout_mvp_experiment,ig_android_direct_pending_media,ig_android_"
			+ "scroll_main_feed,ig_android_intialization_chunk_410,ig_android_story_ads_"
			+ "default_long_video_duration,ig_android_interactions_mention_search_presen"
			+ "ce_dot_universe,ig_android_stories_music_sticker_position,ig_android_dire"
			+ "ct_character_limit,ig_stories_music_themes,ig_android_nametag_save_experi"
			+ "ment_universe,ig_android_media_rows_prepare_10_31,ig_android_fs_new_galle"
			+ "ry,ig_android_stories_hide_retry_button_during_loading_launch,ig_android_"
			+ "remove_follow_all_fb_list,ig_android_biz_conversion_editable_profile_revi"
			+ "ew_universe,ig_android_shopping_checkout_mvp,ig_android_local_info_page,i"
			+ "g_android_direct_log_badge_count";

	/**
	 * Instagram App Version
	 */
	// public static final String APP_VERSION = "22.0.0.15.68";
	public static final String APP_VERSION = "98.0.0.15.119";

	/**
	 * User Locale
	 */
	@Setter
	// public static String LOCALE = "en_US";
	public static String LOCALE = "fr_FR";

	/**
	 * Android Release
	 */
	public static String USER_AGENT = String.format("Instagram %s Android (%s/%s; %s; %s; %s; %s; %s; %s; %s)",
			APP_VERSION, device.getDEVICE_ANDROID_VERSION(), device.getDEVICE_ANDROID_RELEASE(), device.getDPI(),
			device.getDISPLAY_RESOLUTION(), device.getDEVICE_MANUFACTURER(), device.getDEVICE_MODEL(),
			device.getDEVICE(), device.getCPU(), LOCALE);

	public static void setDevice(Device device) {
		InstagramConstants.device = device;
		DEVICE_MANUFACTURER = device.getDEVICE_MANUFACTURER();
		DEVICE_MODEL = device.getDEVICE_MODEL();
		DEVICE_ANDROID_VERSION = device.getDEVICE_ANDROID_VERSION();
		DEVICE_ANDROID_RELEASE = device.getDEVICE_ANDROID_RELEASE();
		USER_AGENT = String.format("Instagram %s Android (%s/%s; %s; %s; %s; %s; %s; %s; %s)", APP_VERSION,
				device.getDEVICE_ANDROID_VERSION(), device.getDEVICE_ANDROID_RELEASE(), device.getDPI(),
				device.getDISPLAY_RESOLUTION(), device.getDEVICE_MANUFACTURER(), device.getDEVICE_MODEL(),
				device.getDEVICE(), device.getCPU(), LOCALE);
	}

}
